language: node_js
node_js:
- node
- '8'
- '7'
- '6'
services:
- xvfb
script:
- npm run test-for-travis
after_success:
- env
- test "${TRAVIS_NODE_VERSION}" == "8" && test "${TRAVIS_TEST_RESULT}" == "0" && npm run build
- ls -la dist/
jobs:
  include:
  - stage: npm release
    node_js: 8
    script:
    - if [ -n "$TRAVIS_TAG" ]; then echo "Deploying version ${TRAVIS_TAG} to npm...";
      fi
    deploy:
      provider: npm
      email: info@labs64.com
      api_key:
        secure: Ap+YAsL47M+RQOI0XIKeeOIvnCkBBFG7w6MdyEIibQjURbI8D9SAhZGEjE2s+ahdmtlwJkcKhPj4hpKNKgPFFSJgrLdtAnfvqoMUuj2LEBc+m7/6eZfUTchV1d7ckKe0PvhvRlQssg04N5ODt65xTPnivRMLiXcPiJDt4AceiR0EwVZQx7YZTSCLx5K48X8HI3VuVwShiWPwxm6zjKGOdoaa6GFO0taUBdUD0wZXHb8bfkHmvgiBz5g/uPoLxs4R6t36mUoXpnte5L9vCwV42Swt1Xmztd1drBUDEjuxmJuLLgNWBZ+Yywn8Z62Zthi+sQ/w99LdFP+CsTExmo+t9CmhakV2OOugonQJmCQdcmh+xWBZNCVCXadjS0yvo/DSm7L+sREiaqn+Y1lCjKAfgcHTi15+fHfDyUOddiW0Yozn2Nje4Oy8zkPjr80X+SoDyoaXa51qM0BV7J7e/e1XBi4sKIqeOOLlRTvJgf2e6/Dqrn/ouMRvqEKafYLynFdPcxszmtoYLuwYt6D8C0blf+Sz6Ofs52oxGZimmMr67am06PiQgMLtUF1Dz5tOlXA1B+aMe6S4Tn+uH4d5pSAPA6vdAXdCYZ62f31Qxd8/M9CsTnLjk87SaOzLd2rF9UV1k1hYlTQl/nKjsbOtKNDQlWzUVCXpvEVXmnRi4HpaYIQ=
      on:
        tags: true
